"""Create bookings table

Revision ID: e0e951dddebd
Revises:
Create Date: 2026-06-22 10:38:38.366941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e0e951dddebd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum("pending", "confirmed", "failed", name="servicetype"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookings")
    # ### end Alembic commands ###
